from pathlib import Path
import numpy as np
import matplotlib.pyplot as plt

Z_BIN_WIDTH_CM = 0.05

# ---- Inputs ----
# Proton seed CSVs (from Section 3.1)
PROTON_GLOB = "../A1_base/DoseZ_seed*.csv"

# Carbon CSVs generated by seed runner
E_STAR = 5102
CARBON_ESTAR_GLOB = f"DoseZ_C_{E_STAR}MeV_seed*.csv"

# Optional slope runs
DO_SLOPE = True
DELTA_E = 25
CARBON_EM_GLOB = f"DoseZ_C_{E_STAR - DELTA_E}MeV_seed*.csv"
CARBON_EP_GLOB = f"DoseZ_C_{E_STAR + DELTA_E}MeV_seed*.csv"

# Tail metric parameters
TAIL_DELTA_CM = 5.0

# Output files
SUMMARY_CSV = Path("G_summary_metrics.csv")
PLOT_PNG = Path("G1_dose_depth_comparison_mean.png")


def load_depth_dose(csv_path: Path):
    data = np.loadtxt(csv_path, comments="#", delimiter=",")
    if data.ndim == 1:
        data = data.reshape(1, -1)

    iz = data[:, 2]
    dose = data[:, 3]
    depth_cm = (iz + 0.5) * Z_BIN_WIDTH_CM
    return depth_cm, dose


def distal_R(depth_cm, dose, level):
    y = dose / np.max(dose)
    i_peak = int(np.argmax(y))
    d = depth_cm[i_peak:]
    yy = y[i_peak:]

    idx = np.where((yy[:-1] >= level) & (yy[1:] < level))[0]
    if len(idx) == 0:
        return float("nan")

    i = idx[0]
    x0, x1 = d[i], d[i + 1]
    y0, y1 = yy[i], yy[i + 1]
    return float(x0 + (level - y0) * (x1 - x0) / (y1 - y0))


def peak_depth_parabolic(depth_cm: np.ndarray, dose: np.ndarray) -> float:
    """
    Sub-bin Bragg peak estimate using a quadratic through (i-1, i, i+1)
    around the maximum dose bin.
    """
    i = int(np.argmax(dose))

    if i == 0 or i == len(dose) - 1:
        return float(depth_cm[i])

    x1, x2, x3 = depth_cm[i - 1], depth_cm[i], depth_cm[i + 1]
    y1, y2, y3 = dose[i - 1], dose[i], dose[i + 1]

    denom = (x1 - x2) * (x1 - x3) * (x2 - x3)
    if denom == 0:
        return float(x2)

    A = (x3 * (y2 - y1) + x2 * (y1 - y3) + x1 * (y3 - y2)) / denom
    B = (x3**2 * (y1 - y2) + x2**2 * (y3 - y1) + x1**2 * (y2 - y3)) / denom

    if A == 0:
        return float(x2)

    x_vertex = -B / (2 * A)
    return float(x_vertex)


def tail_fraction_at_plus(depth_cm, dose, delta_cm):
    y = dose / np.max(dose)
    zp = peak_depth_parabolic(depth_cm, dose)
    zq = zp + delta_cm
    return float(np.interp(zq, depth_cm, y))


def tail_area_beyond_R80(depth_cm, dose):
    y = dose / np.max(dose)
    R80 = distal_R(depth_cm, dose, 0.8)
    if np.isnan(R80):
        return float("nan")

    mask = depth_cm >= R80
    area_total = float(np.trapezoid(y, depth_cm))
    area_tail = float(np.trapezoid(y[mask], depth_cm[mask]))
    return area_tail / area_total


def mean_and_sd(vals):
    vals = np.array(vals, dtype=float)
    mu = float(np.mean(vals))
    sd = float(np.std(vals, ddof=1)) if len(vals) > 1 else 0.0
    return mu, sd


def load_many(glob_pattern):
    files = sorted(Path(".").glob(glob_pattern))
    if not files:
        raise RuntimeError(f"No files matched: {glob_pattern}")
    return files


def resample_to_grid(z, y, z_grid):
    return np.interp(z_grid, z, y)


def analyse_group(files, label):
    zpeaks, R80s, R90s, Tail5s, TailAs = [], [], [], [], []
    curves = []

    for f in files:
        z, d = load_depth_dose(f)
        y = d / np.max(d)
        curves.append((z, y))

        zpeaks.append(peak_depth_parabolic(z, d))
        R80s.append(distal_R(z, d, 0.8))
        R90s.append(distal_R(z, d, 0.9))
        Tail5s.append(tail_fraction_at_plus(z, d, TAIL_DELTA_CM))
        TailAs.append(tail_area_beyond_R80(z, d))

    zpeak_mean, zpeak_sd = mean_and_sd(zpeaks)
    R80_mean, R80_sd = mean_and_sd(R80s)
    R90_mean, R90_sd = mean_and_sd(R90s)
    Tail5_mean, Tail5_sd = mean_and_sd(Tail5s)
    TailArea_mean, TailArea_sd = mean_and_sd(TailAs)

    out = {
        "label": label,
        "n": len(files),
        "zpeak_mean": zpeak_mean,
        "zpeak_sd": zpeak_sd,
        "R80_mean": R80_mean,
        "R80_sd": R80_sd,
        "R90_mean": R90_mean,
        "R90_sd": R90_sd,
        "Tail5_mean": Tail5_mean,
        "Tail5_sd": Tail5_sd,
        "TailArea_mean": TailArea_mean,
        "TailArea_sd": TailArea_sd,
        "curves": curves,
    }
    return out


def make_mean_curve(curves, z_grid):
    Ys = np.array([resample_to_grid(z, y, z_grid) for (z, y) in curves], dtype=float)
    y_mean = np.mean(Ys, axis=0)
    y_sd = np.std(Ys, axis=0, ddof=1) if Ys.shape[0] > 1 else np.zeros_like(y_mean)
    return y_mean, y_sd


def main():
    proton_files = load_many(PROTON_GLOB)
    carbon_files = load_many(CARBON_ESTAR_GLOB)

    proton = analyse_group(proton_files, "proton_220MeV")
    carbon = analyse_group(carbon_files, f"carbon_{E_STAR}MeV")

    print("\n=== Bragg peak depth (mean ± SD) ===")
    print(f"Proton (n={proton['n']}): z_peak={proton['zpeak_mean']:.4f} ± {proton['zpeak_sd']:.4f} cm")
    print(f"Carbon (n={carbon['n']}): z_peak={carbon['zpeak_mean']:.4f} ± {carbon['zpeak_sd']:.4f} cm")

    print("\n=== R80/R90 (mean ± SD) ===")
    print(f"Proton (n={proton['n']}): R80={proton['R80_mean']:.4f} ± {proton['R80_sd']:.4f} cm, "
          f"R90={proton['R90_mean']:.4f} ± {proton['R90_sd']:.4f} cm")
    print(f"Carbon (n={carbon['n']}): R80={carbon['R80_mean']:.4f} ± {carbon['R80_sd']:.4f} cm, "
          f"R90={carbon['R90_mean']:.4f} ± {carbon['R90_sd']:.4f} cm")

    print("\n=== Tail metrics (mean ± SD), normalized ===")
    print(f"Tail5 = D(z_peak+{TAIL_DELTA_CM:.0f}cm)/Dmax:")
    print(f"  Proton: {proton['Tail5_mean']:.6f} ± {proton['Tail5_sd']:.6f}")
    print(f"  Carbon: {carbon['Tail5_mean']:.6f} ± {carbon['Tail5_sd']:.6f}")
    print("TailArea beyond R80 (fraction of total normalized area):")
    print(f"  Proton: {proton['TailArea_mean']:.6f} ± {proton['TailArea_sd']:.6f}")
    print(f"  Carbon: {carbon['TailArea_mean']:.6f} ± {carbon['TailArea_sd']:.6f}")

    # --- Optional local slope and sigma_E using z_peak, not R80 ---
    sigma_E = None
    slope = None
    if DO_SLOPE:
        em_files = sorted(Path(".").glob(CARBON_EM_GLOB))
        ep_files = sorted(Path(".").glob(CARBON_EP_GLOB))

        if em_files and ep_files:
            em = analyse_group(em_files, f"carbon_{E_STAR - DELTA_E}MeV")
            ep = analyse_group(ep_files, f"carbon_{E_STAR + DELTA_E}MeV")

            slope = (ep["zpeak_mean"] - em["zpeak_mean"]) / (2 * DELTA_E)  # cm/MeV
            if slope != 0:
                sigma_E = carbon["zpeak_sd"] / abs(slope)

            print("\n=== Local slope and σ_E from Bragg peak depth (optional) ===")
            print(f"z_peak(E*-ΔE)={em['zpeak_mean']:.4f} cm, z_peak(E*+ΔE)={ep['zpeak_mean']:.4f} cm, ΔE={DELTA_E} MeV")
            print(f"dz_peak/dE ≈ {slope:.6e} cm/MeV")
            if sigma_E is not None:
                print(f"σ_E ≈ σ_z / |dz/dE| = {sigma_E:.2f} MeV")
        else:
            print("\n(Note) Slope files not found; skipping σ_E. Generate E*±ΔE carbon runs if desired.")

    # --- Build mean curves and plot ---
    z_grid = (np.arange(800) + 0.5) * Z_BIN_WIDTH_CM

    yp_mean, yp_sd = make_mean_curve(proton["curves"], z_grid)
    yc_mean, yc_sd = make_mean_curve(carbon["curves"], z_grid)

    zpeak_p = proton["zpeak_mean"]
    zpeak_c = carbon["zpeak_mean"]
    R80_p, R90_p = proton["R80_mean"], proton["R90_mean"]
    R80_c, R90_c = carbon["R80_mean"], carbon["R90_mean"]

    plt.figure(figsize=(10, 6))
    plt.plot(z_grid, yp_mean, label="Proton 220 MeV")
    plt.plot(z_grid, yc_mean, label=f"Carbon {E_STAR} MeV (matched)")

    plt.fill_between(z_grid, yp_mean - yp_sd, yp_mean + yp_sd, alpha=0.2)
    plt.fill_between(z_grid, yc_mean - yc_sd, yc_mean + yc_sd, alpha=0.2)

    # Bragg peak markers
    plt.axvline(zpeak_p, linestyle="--", label="Proton Bragg peak")
    plt.axvline(zpeak_c, linestyle=":", label="Carbon Bragg peak")

    '''# Optional distal markers
    plt.axvline(R80_p, linestyle="--", alpha=0.5, label="Proton R80/R90")
    plt.axvline(R90_p, linestyle="--", alpha=0.5)
    plt.axvline(R80_c, linestyle=":", alpha=0.5, label="Carbon R80/R90")
    plt.axvline(R90_c, linestyle=":", alpha=0.5)'''

    plt.xlabel("Depth in water (cm)", fontsize=14)
    plt.ylabel("Dose (normalized to max)", fontsize=14)
    plt.title("Dose–depth comparison (mean ± SD): Proton 220 MeV vs matched Carbon (Bragg peak)")
    plt.xticks(fontsize=12)
    plt.yticks(fontsize=12)
    plt.grid(True)
    plt.legend(fontsize=11)
    plt.tight_layout()
    plt.savefig(PLOT_PNG, dpi=300)
    plt.show()

    # --- Save summary table ---
    header = [
        "group", "n",
        "zpeak_mean_cm", "zpeak_sd_cm",
        "R80_mean_cm", "R80_sd_cm",
        "R90_mean_cm", "R90_sd_cm",
        f"Tail5_mean_(+{int(TAIL_DELTA_CM)}cm)", f"Tail5_sd_(+{int(TAIL_DELTA_CM)}cm)",
        "TailArea_mean_beyondR80", "TailArea_sd_beyondR80",
        "dzpeakdE_cm_per_MeV", "sigma_E_MeV"
    ]

    rows = []
    for g in (proton, carbon):
        rows.append([
            g["label"], g["n"],
            g["zpeak_mean"], g["zpeak_sd"],
            g["R80_mean"], g["R80_sd"],
            g["R90_mean"], g["R90_sd"],
            g["Tail5_mean"], g["Tail5_sd"],
            g["TailArea_mean"], g["TailArea_sd"],
            slope if slope is not None else np.nan,
            sigma_E if sigma_E is not None else np.nan
        ])

    with open(SUMMARY_CSV, "w") as f:
        f.write(",".join(header) + "\n")
        for r in rows:
            f.write(",".join(str(x) for x in r) + "\n")

    print(f"\nSaved plot: {PLOT_PNG}")
    print(f"Saved summary table: {SUMMARY_CSV}")


if __name__ == "__main__":
    main()